### PR TITLE
Modified error

### LINKED ISSUE #69: [BUG] Body response object for error message.
**Describe the bug**
Add a separate attribute in the response object for error message don't pass it under the body.

Area Where Bug Occurred
- [X] Lambda <@ALL>
- [ ] DynamodDb

**How to reproduce the error/bug**
```
function response(statusCode, message, errorMessage) {
  return {
    statusCode: statusCode,
    body: message,
    error: errorMessage
  };
}
```

**Additional context**
Status code for Error: 500
Error Message: "Internal Server Error"

**Before submitting an issue check the below**
- [X] I have synced all my node versions as mentioned in the project"
- [X] I am using the same version of npm as is the project

### PR DESCRIPTION
**Pull request by ayush0x00**
# Description

Modified response body
Fixes #69 

## Type of change

Please delete options that are not relevant.

- [x] Updated lambda `@<name of the lambda>`
- [ ] Created new lambda `@<name of the lambda>`
- [ ] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: lambdas/url_access_patterns/lambda_for_updateURL/index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 const AWS = require("aws-sdk");
 const dynamo = new AWS.DynamoDB.DocumentClient();+
```
Comment (lakshya-20) [inline lambdas/url_access_patterns/lambda_for_updateURL/index.js]: Remove the trailing +

File: lambdas/url_access_patterns/lambda_for_deleteURL/index.js [hunk 2]
```diff
@@ -19,9 +19,9 @@ exports.handler = async (event) =>{
             }
         }
         await dynamo.delete(params).promise();
-        return  response(201,message="URL delete success");
+        return  response(201,undefined,"URL delete success");
     }
     catch(err){
-        return response(500,error="Internal Server Error");;
+        return response(500,"Internal Server Error",undefined);;
```
Comment (lakshya-20) [inline lambdas/url_access_patterns/lambda_for_deleteURL/index.js]: Remove extra `;`

**Review by lakshya-20 — CHANGES_REQUESTED** [review]
There are so many `;;` at different places. Resolve them.

File: lambdas/file_access_patterns/lambda_for_fileUpload/index.js [hunk 3]
```diff
@@ -53,9 +53,9 @@ exports.handler = async (event) => {
         ":file_size": reqBody.f_size,
```
Comment (lakshya-20) [inline lambdas/file_access_patterns/lambda_for_fileUpload/index.js]: `":file_size": reqBody.f_size,` make it to `":file_size": reqBody.size,`

**Review by lakshya-20 — CHANGES_REQUESTED** [review]
