### PR TITLE
Default url on file upload implemented

### LINKED ISSUE #65: [BUG] auto generate url when file is uploaded
**Describe the bug**
As the main motive of this application is an easy and fast way of sharing files. The current implementation allows users to upload files and then separately generate URLs, instead what should be done is their must one URL which is the default one and it is autogenerated whenever the file is uploaded, it will be a public URL and be included in the files model itself. In this way, every time a user uploads a file he/she gets the default URL making the user experience better.

**Before submitting an issue check the below**
- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project

### PR DESCRIPTION
**Pull request by danishjamal104**
# Description
Below are the changes:
1. Since file upload includes multiple write request hence query move to `transactWrite`.
2. Added permission for invoking `lambda_for_generateURL`.
3. Modified file schema to include `default: <default URL of file>`.
4. Modified `lambda_for_generateURL` to support the `INVOKE` method. Now it returns the `params` without making the database request when `event.method` is set to `INVOKE`

Fixes #65 

## Type of change

Please delete options that are not relevant.

- [x] Updated lambda `@lambda_for_fileUpload and @lambda_for_generateURL`
- [ ] Created new lambda `@<name of the lambda>`
- [ ] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by ayush0x00 — APPROVED** [review]

**Comment by danishjamal104** [comment]
I think we can merge this now?

File: lambdas/file_access_patterns/lambda_for_fileUpload/index.js [hunk 1]
```diff
@@ -31,31 +49,31 @@ exports.handler = async (event) => {
...
+  let generateUrlTask;
+  const params = { FunctionName: 'lambda_for_generateURL', InvocationType: 'RequestResponse',
+    Payload: getGenerateUrlPayload(file.hash, file.SK.split('#')[1])
   }
-  catch(err){
-    return response(500,"Internal Server Error",undefined);
+  try {
+    const res = await Lambda.invoke(params).promise()
+    generateUrlTask = JSON.parse(res.Payload)
+  } catch(err) { return response(500, JSON.stringify(err), undefined) }
```
Comment (lakshya-20) [inline lambdas/file_access_patterns/lambda_for_fileUpload/index.js]: Return `Internal Server Error` as the error message.

File: lambdas/file_access_patterns/lambda_for_fileUpload/index.js [hunk 2]
```diff
@@ -31,31 +49,31 @@ exports.handler = async (event) => {
...
+    TransactItems: [{ Put: filePutTask }, { Update: userMetaDataUpdateTask }, { Put: generateUrlTask }]
   }
-  catch(err){
-    return response(500,"Internal Server Error",undefined);
+
+  try {
+    await dynamo.transactWrite(param).promise()
+    return response(200, undefined, file)
+  } catch (err) {
+    return response(500, JSON.stringify(err), undefined)
```
Comment (lakshya-20) [inline lambdas/file_access_patterns/lambda_for_fileUpload/index.js]: Return `Internal Server Error` as the error message.

**Review by lakshya-20 — CHANGES_REQUESTED** [review]

File: lambdas/url_access_patterns/lambda_for_generateURL/index.js [hunk 3]
```diff
@@ -46,6 +46,10 @@ exports.handler = async (event) => {
     TableName: "V-Transfer",
     Item: url,
   }
+  // if event.method is 'INVOKE' then dynamo call is not made and params is returned
+  if(event.method == 'INVOKE') {
+    return params
+  }
```
Comment (lakshya-20) [inline lambdas/url_access_patterns/lambda_for_generateURL/index.js:52]: Instead of returning query parameters that are to be executed in `fileUpload lambda`, can we do the put operation in this `generateURL lambda` and return only the `GS1_PK` when the `event.method == "Invoke"` .

File: lambdas/file_access_patterns/lambda_for_fileUpload/index.js (hunk 1 above)
Comment (danishjamal104) [reply lambdas/file_access_patterns/lambda_for_fileUpload/index.js]: updated please check. Thanks

File: lambdas/file_access_patterns/lambda_for_fileUpload/index.js (hunk 2 above)
Comment (danishjamal104) [reply lambdas/file_access_patterns/lambda_for_fileUpload/index.js]: this also

**Comment by danishjamal104** [comment]
I have removed the `out/` directory
